version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: Abc1234_
      TZ: Europe/Berlin
    logging:
      driver: none
    networks:
      - nse_dev

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5001:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.root
      PGADMIN_DEFAULT_PASSWORD: Abc1234_
      TZ: Europe/Berlin
    logging:
      driver: none
    networks:
      - nse_dev

volumes:
  postgres-data:
  pgadmin-data:

networks:
  nse_dev:
    driver: bridge
